{
    "id": "LUCENE-6136",
    "title": "IndexAndTaxonomyReplicationClientTest.testConsistencyOnExceptions failure",
    "details": {
        "resolution": "Unresolved",
        "affect_versions": "None",
        "components": [],
        "labels": "",
        "fix_versions": [],
        "priority": "Major",
        "status": "Open",
        "type": "Test"
    },
    "description": "This reproduces on 4.10:\n\nant test  -Dtestcase=IndexAndTaxonomyReplicationClientTest -Dtests.method=testConsistencyOnExceptions -Dtests.seed=DFD235D80B3C7F11 -Dtests.multiplier=3 -Dtests.slow=true -Dtests.locale=be_BY -Dtests.timezone=Atlantic/Reykjavik -Dtests.file.encoding=ISO-8859-1",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "id": "comment-14258575",
            "author": "Robert Muir",
            "date": "2014-12-24T22:47:19+0000",
            "content": "exception is hit writing segments_k, but then the delete fails, twice (once in Directory.copy's finally block, then again in cleanupFilesOnFailure).\n\nbecause this segments_k cannot be deleted, then checkindex goes to use it, and gets a bunch of FNFE, as expected.\n\nthe bug is not possible in 5.x because segments_N is written atomically there. in 4.x there is not much that can be done IMO. "
        }
    ]
}