{
    "id": "SOLR-12229",
    "title": "Harden exception handling in CdcrUpdateLogSynchronizer",
    "details": {
        "labels": "",
        "priority": "Major",
        "components": [
            "CDCR"
        ],
        "type": "Bug",
        "fix_versions": [],
        "affect_versions": "None",
        "resolution": "Unresolved",
        "status": "Open"
    },
    "description": "In CdcrUpdateLogSynchronizer when we ask for the last processed version, if the call fails and we don't catch the exception the synchronizer can quit.\n\n\u00a0\n\nHere's an example from a Jenkins failure\u00a0\n\n[junit4] 2> 2810643 WARN (cdcr-update-log-synchronizer-9646-thread-1) [ ] o.a.s.h.CdcrUpdateLogSynchronizer Caught unexpected exception\n[junit4] 2> org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://127.0.0.1:45384/solr/cdcr-source_shard1_replica_n1: SolrCore is loading\n[junit4] 2> at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:643) ~[java/:?]\n[junit4] 2> at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255) ~[java/:?]\n[junit4] 2> at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244) ~[java/:?]\n[junit4] 2> at org.apache.solr.client.solrj.SolrClient.request(SolrClient.java:1219) ~[java/:?]\n[junit4] 2> at org.apache.solr.handler.CdcrUpdateLogSynchronizer$UpdateLogSynchronisation.run(CdcrUpdateLogSynchronizer.java:147) [java/:?]\n[junit4] 2> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]\n[junit4] 2> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_162]\n[junit4] 2> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_162]\n[junit4] 2> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_162]\n[junit4] 2> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]\n[junit4] 2> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]\n[junit4] 2> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]\n\nWe should audit the code usage and then harden the failure scenarios and deal with it more gracefully",
    "attachments": {
        "jenkins-build561.log": "https://issues.apache.org/jira/secure/attachment/12919253/jenkins-build561.log"
    },
    "issue_links": {},
    "comments": []
}