{
    "id": "SOLR-7185",
    "title": "null pointer exception at AbstractSolrSecondaryIndex.java",
    "details": {
        "components": [
            "search"
        ],
        "type": "Bug",
        "labels": "",
        "fix_versions": [],
        "affect_versions": "4.6",
        "status": "Resolved",
        "resolution": "Invalid",
        "priority": "Minor"
    },
    "description": "a few hundreds of the following NPE were reported in the system.log:\n\nINFO [SolrSecondaryIndex ax.account_freq_accessed TTL scheduler.] 2015-03-02 17:38:19,435 AbstractSolrSecondaryIndex.java (line 1491) Found 4 rows with expired columns.\nWARN [SolrSecondaryIndex ax.account_freq_accessed TTL scheduler.] 2015-03-02 17:38:19,436 AbstractSolrSecondaryIndex.java (line 1505) \njava.lang.NullPointerException\nat com.datastax.bdp.search.solr.Cql3SolrSecondaryIndex.buildIndexedColumnFamily(Cql3SolrSecondaryIndex.java:98)\nat com.datastax.bdp.search.solr.AbstractSolrSecondaryIndex.doApplyUpdates(AbstractSolrSecondaryIndex.java:932)\nat com.datastax.bdp.search.solr.AbstractSolrSecondaryIndex.access$1300(AbstractSolrSecondaryIndex.java:94)\nat com\n.datastax.bdp.search.solr.AbstractSolrSecondaryIndex$TTLIndexRebuildTask.run(AbstractSolrSecondaryIndex.java:1501)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\n\tat java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n\tat java.lang.Thread.run(Thread.java:745)\n WARN [SolrSecondaryIndex ax.account_freq_accessed TTL scheduler.] 2015-03-02 17:38:19,436 AbstractSolrSecondaryIndex.java (line 1505) \njava.lang.NullPointerException\n\tat com.datastax.bdp.search.solr.Cql3SolrSecondaryIndex.buildIndexedColumnFamily(Cql3SolrSecondaryIndex.java:98)\n\tat com.datastax.bdp.search.solr.AbstractSolrSecondaryIndex.doApplyUpdates(AbstractSolrSecondaryIndex.java:932)\n\tat com.datastax.bdp.search.solr.AbstractSolrSecondaryIndex.access$1300(AbstractSolrSecondaryIndex.java:94)\n\tat com.datastax.bdp.search.solr.AbstractSolrSecondaryIndex$TTLIndexRebuildTask.run(AbstractSolrSecondaryIndex.java:1501)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\n\tat java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n\tat java.lang.Thread.run(Thread.java:745)",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "date": "2015-03-03T17:27:11+0000",
            "author": "Shalin Shekhar Mangar",
            "content": "Hi Massimo, that error is from the DataStax fork of Solr. Please report this bug to DataStax. I am closing this issue. ",
            "id": "comment-14345367"
        },
        {
            "date": "2015-03-03T17:29:02+0000",
            "author": "MASSIMO CELLI",
            "content": "apologies I created this in error on the Solr open source jira ",
            "id": "comment-14345369"
        }
    ]
}